import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Plugin to copy WASM files and handle MathBox CSS after build
const copyAssetsPlugin = {
	name: 'copy-assets',
	setup(build) {
		build.onEnd(() => {
			// Copy WASM module
			const wasmSource = resolve('src/wasm/math_engine.js');
			const wasmDest = resolve('math_engine.js');
			
			if (existsSync(wasmSource)) {
				copyFileSync(wasmSource, wasmDest);
				console.log('✓ Copied WASM module to output directory');
			} else {
				console.warn('⚠ WASM module not found. Run build-plugin.sh to compile C++ code first.');
			}

			// Copy MathBox CSS to styles.css
			const mathboxCssPath = resolve('node_modules/mathbox/build/mathbox.css');
			const stylesPath = resolve('styles.css');
			
			if (existsSync(mathboxCssPath)) {
				const mathboxCss = readFileSync(mathboxCssPath, 'utf-8');
				const existingStyles = existsSync(stylesPath) ? readFileSync(stylesPath, 'utf-8') : '';
				
				// Only append if not already included
				if (!existingStyles.includes('/* MathBox Core Styles */')) {
					const combinedStyles = existingStyles + '\n\n/* MathBox Core Styles */\n' + mathboxCss;
					writeFileSync(stylesPath, combinedStyles);
					console.log('✓ Added MathBox CSS to styles.css');
				}
			} else {
				console.warn('⚠ MathBox CSS not found. Install dependencies first.');
			}
		});
	}
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		"./math_engine.js",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [copyAssetsPlugin],
	loader: {
		'.wasm': 'file',
		'.css': 'text',
	},
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
