
// Define minimal types for the Emscripten module
interface MathModule {
    HEAPF64: Float64Array;
    calculate3D: (formula: string, xMin: number, xMax: number, yMin: number, yMax: number, res: number) => GraphResult;
    getPathData3D: (result: GraphResult) => Float64Array; // Returns view
    // Memory management
    _malloc: (size: number) => number;
    _free: (ptr: number) => void;
}

interface GraphResult {
    success: boolean;
    errorMessage: string;
    path: any; // C++ vector
    delete: () => void;
}

declare global {
    function createMathModule(): Promise<MathModule>;
}

export class WasmComputer {
    private module: MathModule | null = null;
    private isInitializing = false;

    constructor() {
        this.init();
    }

    async init() {
        if (this.module || this.isInitializing) return;
        this.isInitializing = true;

        try {
            // Load the script if not already loaded (in a real app, this might be handled by a loader)
            // For now, assume global createMathModule is available from the script tag 
            // or imported if using a specific loader. 
            // In this setup, we'll likely load the WASM JS file via a script tag in index.html for simplicity 
            // or dynamic import if Vite supports it well for non-ESM Emscripten output.

            // Dynamic import of the file generated by Emscripten
            // Note: This path depends on how Vite serves public assets.
            // @ts-ignore
            if (typeof createMathModule === 'undefined') {
                // Fallback or wait for script load
                console.warn("createMathModule not defined. Ensure script is loaded.");
                return;
            }

            this.module = await createMathModule();
            console.log("WASM Module Initialized");
        } catch (e) {
            console.error("Failed to init WASM", e);
        } finally {
            this.isInitializing = false;
        }
    }

    public calculate(formula: string, range: { xMin: number, xMax: number, yMin: number, yMax: number }, resolution: number = 100) {
        if (!this.module) {
            console.warn("WASM not ready");
            return null;
        }

        // 1. Calculate in C++
        const result = this.module.calculate3D(
            formula,
            range.xMin, range.xMax,
            range.yMin, range.yMax,
            resolution
        );

        if (!result.success) {
            console.error("Math Error:", result.errorMessage);
            result.delete();
            return null;
        }

        // 2. Zero-Copy Extraction
        // getPathData3D returns a Float64Array view directly on WASM heap
        const dataView = this.module.getPathData3D(result);

        // Check if empty
        if (!dataView || dataView.length === 0) {
            result.delete();
            return null;
        }

        // IMPORTANT: We must NOT delete 'result' immediately if we want to use the view, 
        // BUT 'getPathData3D' usually returns a view into the vector inside 'result'.
        // If we return the view to the caller, we must be careful about validity.
        // 
        // Option A: Copy here (Not Zero-Copy to JS, but safer).
        // Option B: Return the view and give responsibility to caller to delete 'result' later.
        // Option C: Copy into a reusable TypedArray on JS side (Fast Copy).

        // For 'Zero-Copy' into Three.js BufferAttribute, we need Float32Array usually.
        // Our C++ returns doubles (Float64). Three.js Buffers are usually Float32.
        // So we MUST convert/copy Float64 -> Float32. 
        // True Zero-Copy is only possible if C++ uses floats (Float32) or Three.js accepts Float64Attribute (rare/newer).
        // 
        // Decision: High-speed copy Float64 -> Float32.
        const f32 = new Float32Array(dataView);

        // Cleanup C++ object (the vector)
        result.delete();

        return f32;
    }
}
